FROM mcr.microsoft.com/dotnet/sdk:10.0
WORKDIR /src
COPY . .
RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"
ENV ConnectionStrings__IPNoteDb="Data Source=/data/ipnote.db"
RUN mkdir -p /data
ENTRYPOINT ["dotnet", "ef", "database", "update", "--project", "src/Infrastructure/Infrastructure.csproj", "--startup-project", "src/Web/Web.csproj", "--configuration", "Release"]
