swagger_parser:
  schema_path: openapi/v1.json
  output_directory: lib/api/generated
  name: ipnote
  language: dart
  json_serializer: json_serializable
  root_client: false
  merge_clients: true
  put_in_folder: true
  put_clients_in_folder: true
  export_file: true
  include_tags:
    - IpLookup
    - IpNotes
    - Users
    - PushDevice
  mark_files_as_generated: true
