using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;

namespace Ntk.Note.IP.Web.Infrastructure;

/// <summary>
/// Adds human-readable summaries and descriptions to the ASP.NET Core Identity endpoints
/// registered by <c>MapIdentityApi</c>. Those endpoints are generated by the framework and
/// cannot be annotated with <see cref="EndpointSummaryAttribute"/> or
/// <see cref="EndpointDescriptionAttribute"/> directly, so metadata is applied here by
/// matching on the operation's relative path (and HTTP method for ambiguous paths).
/// </summary>
internal sealed class IdentityApiOperationTransformer : IOpenApiOperationTransformer
{
    private static readonly Dictionary<string, (string Summary, string Description)> _metadata = new()
    {
        ["api/v1/Users/register"]                  = ("Register", "Creates a new user account."),
        ["api/v1/Users/login"]                     = ("Log in", "Authenticates a user. Use ?useCookies=true for cookie-based authentication."),
        ["api/v1/Users/refresh"]                   = ("Refresh token", "Returns a new access token using a valid refresh token."),
        ["api/v1/Users/confirmEmail"]              = ("Confirm email", "Confirms a user's email address using the token sent by email."),
        ["api/v1/Users/resendConfirmationEmail"]   = ("Resend confirmation email", "Sends a new email confirmation link to the specified address."),
        ["api/v1/Users/forgotPassword"]            = ("Forgot password", "Sends a password reset link to the specified email address."),
        ["api/v1/Users/resetPassword"]             = ("Reset password", "Resets a user's password using the token sent by email."),
        ["api/v1/Users/manage/2fa"]                = ("Manage two-factor authentication", "Enables, disables, or retrieves two-factor authentication settings."),
        ["api/v1/Users/manage/info GET"]           = ("Get account info", "Returns the current user's email and two-factor authentication status."),
        ["api/v1/Users/manage/info POST"]          = ("Update account info", "Updates the current user's email or password."),
    };

    public Task TransformAsync(OpenApiOperation operation, OpenApiOperationTransformerContext context, CancellationToken cancellationToken)
    {
        var path = context.Description.RelativePath ?? "";
        var key = $"{path} {context.Description.HttpMethod?.ToUpperInvariant()}";

        if (_metadata.TryGetValue(key, out var meta) || _metadata.TryGetValue(path, out meta))
        {
            operation.Summary = meta.Summary;
            operation.Description = meta.Description;
        }

        return Task.CompletedTask;
    }
}